selected_keys = [
    "Absorptance",
    "Actual Number of Risers",
    "Actual Number of Treads",
    "Actual Riser Height",
    "Actual Run Width",
    "Actual Tread Depth",
    "Analytical Properties.Absorptance",
    "Analytical Properties.Heat Transfer Coefficient (U)",
    "Analytical Properties.Roughness",
    "Analytical Properties.Thermal Mass",
    "Analytical Properties.Thermal Resistance (R)",
    "Area",
    "Bar Diameter",
    "Base Constraint",
    "Bauteilart",
    "Bauteilklasse",
    "Breite",
    "Category",
    "Classification Description",
    "Color",
    "Construction Type",
    "Construction.Function",
    "Construction.Lage Aussen",
    "Construction.Profile",
    "ConstructionType",
    "Data.Form Tür",
    "Data.Unternehmer",
    "Description",
    "Dicke",
    "Door Material",
    "Elevation at Bottom",
    "Elevation from Level",
    "ExtendToStructure",
    "Family",
    "Family and Type",
    "Features",
    "Feuerwiderstandsklasse",
    "Finish",
    "Fire protection",
    "Fire resistance class",
    "FireIsolationMaterial",
    "FireRating",
    "Fluchttür",
    "Fläche",
    "Foundation Thickness",
    "Frame Material",
    "Function",
    "Geschoss ID",
    "Gewerbebau.Bauteilart",
    "Gewerbebau.Bauteilklasse",
    "Gewerbebau.Feuerwiderstandsklasse",
    "Gewerbebau.Material",
    "Gewerbebau.Typname",
    "Gewerbebau.Türbezeichnung",
    "Glasfläche",
    "GlazingAreaFraction",
    "H",
    "Heat Transfer Coefficient (U)",
    "Height",
    "Host",
    "Höhe ",
    "Identity Data.Assembly Description",
    "Identity Data.Description",
    "Identity Data.Feuerwiderstandsklasse",
    "Identity Data.Fire Rating",
    "Identity Data.Manufacturer",
    "Identity Data.OmniClass Title",
    "Identity Data.Type Name",
    "Identity Data.Workset",
    "IsExternal",
    "IsFireExit",
    "L",
    "Lage Aussen ",
    "Layers.EN Layers and Widths",
    "Length",
    "Level",
    "LoadBearing",
    "Location Line",
    "Länge",
    "Manufacturer",
    "Material",
    "Material Quality",
    "Materials and Finishes.Flügel",
    "Materials and Finishes.Glas",
    "Materials and Finishes.Konstruktion",
    "Materials and Finishes.Markierung",
    "Materials and Finishes.Material Kuppelglas",
    "Materials and Finishes.Rahmen",
    "Materials and Finishes.Riser Material",
    "Materials and Finishes.Structural Material",
    "Materials and Finishes.Tread Material",
    "Materials and Finishes.Überbeton Material",
    "OmniClass Number",
    "OmniClass Title",
    "Other.Category",
    "Other.Family Name",
    "Perimeter",
    "Phase Created",
    "Pset_ConcreteElementGeneral.ConstructionType",
    "Pset_ConcreteElementGeneral.FireRating",
    "Pset_ProductRequirements.Category",
    "Pset_QuantityTakeOff.Reference",
    "Pset_StairFlightCommon.Reference",
    "Pset_WallCommon.IsExternal",
    "Pset_WallCommon.ThermalTransmittance",
    "Reference",
    "Related to Mass",
    "Room Bounding",
    "Roughness",
    "Shape",
    "Size",
    "Span",
    "Standard Bend Diameter",
    "Structural",
    "Structural Area",
    "Structural Material",
    "Structural Usage",
    "Structural.Filter Tragend / Nichttragend",
    "Thermal mass",
    "Thermal Resistance (R)",
    "ThermalTransmittance",
    "Thickness",
    "Tragende",
    "Type",
    "Type Id",
    "Typname",
    "Türbezeichnung",
    "Umfang",
    "unter Terrain",
    "Volume",
    "Volumen",
    "Wandstärke",
    "Width",
    "Workset",
]
